=== raghavendraphayde95/doxdb/doxdb-rest/src/main/resources/META-INF/xsd/dox.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://doxdb.trajano.net/schema/"
	xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:extensionBindingPrefixes="xjc" targetNamespace="http://doxdb.trajano.net/schema/"
	jxb:version="2.0" attributeFormDefault="unqualified"
	elementFormDefault="qualified">
	<annotation>
		<appinfo>
			<jxb:globalBindings generateIsSetMethod="true">
				<xjc:serializable uid="20150101" />
			</jxb:globalBindings>
		</appinfo>
	</annotation>
	<element name="dox-persistence">
		<complexType>
			<sequence>
				<element type="tns:CollectionType" name="collection" minOccurs="1"
					maxOccurs="unbounded" />
				<element type="tns:IndexType" name="index" minOccurs="0"
					maxOccurs="unbounded" />
			</sequence>
			<attribute name="elasticSearchUri" type="anyURI" use="optional"
				default="http://localhost:9200">
				<annotation>
					<appinfo>
						<jxb:property>
							<jxb:javadoc>URI to the Elasticsearch server.</jxb:javadoc>
						</jxb:property>
					</appinfo>
				</annotation>
			</attribute>
			<attribute name="cors" type="string" use="optional">
				<annotation>
					<appinfo>
						<jxb:property>
							<jxb:javadoc>Defines the value of the CORS header.</jxb:javadoc>
						</jxb:property>
					</appinfo>
				</annotation>
			</attribute>
		</complexType>
		<unique name="uniqueName">
			<selector xpath="collection" />
			<field xpath="@name" />
		</unique>
	</element>
	<complexType name="CollectionType">
		<sequence>
			<element name="schema" type="tns:SchemaType" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="NMTOKEN" use="required" />
		<attribute name="size" type="positiveInteger" default="1073741824">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Size of the content in bytes. Defaults to 1GB.
						</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
		<attribute name="oob" type="boolean" default="false">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Indicates whether OOB tables should be created.
						</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
		<attribute name="readAll" type="tns:ReadAllType" default="memory">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>If not "none", this will allow access to the readAll
							method for the collection.
						</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
		<attribute name="oobSize" type="positiveInteger" default="2147483647">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Size of an OOB in bytes. Defaults to 2GB. Ignored if
							oob is false.
						</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
		<attribute name="lockable" type="boolean" default="false">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Indicates whether locks are required to make updates to the dox record.</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
	</complexType>
	<simpleType name="ReadAllType">
		<restriction base="token">
			<enumeration value="memory"></enumeration>
			<enumeration value="file"></enumeration>
			<enumeration value="none"></enumeration>
		</restriction>
	</simpleType>
	<complexType name="SchemaType">
		<annotation>
			<appinfo>
				<jxb:class>
					<jxb:javadoc>A schema definition.</jxb:javadoc>
				</jxb:class>
			</appinfo>
		</annotation>
		<sequence>
			<element name="oob" type="token" minOccurs="0" maxOccurs="unbounded" />
			<element name="unique" type="tns:LookupType" minOccurs="0" maxOccurs="unbounded" />
			<element name="lookup" type="tns:LookupType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="version" type="positiveInteger" use="required">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Specifies the version identifier for the schema.
						</jxb:javadoc>
						<jxb:baseType name="java.lang.Integer" />
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
		<attribute name="location" use="required">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Location of the JSON schema. It is relative to the
							"META-INF/schema" path. Using an absolute or ".." is not
							supported and may yield unexpected results.
						</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
			<simpleType>
				<restriction base="anyURI"></restriction>
			</simpleType>
		</attribute>
	</complexType>
	<complexType name="IndexType">
		<attribute name="name" type="token" use="required">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Name of the index
						</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
		<attribute name="mappedName" type="token" use="optional">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Name of the physical index if it is not the same as
							'name'.
						</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="LookupType">
		<attribute name="name" type="token" use="required">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Name of the  lookup
						</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
		<attribute name="path" type="token" use="required">
			<annotation>
				<appinfo>
					<jxb:property>
						<jxb:javadoc>Json Path to the value for the lookup key.</jxb:javadoc>
					</jxb:property>
				</appinfo>
			</annotation>
		</attribute>
	</complexType>
</schema>

=== raghavendraphayde95/doxdb/doxdb-sample-web/src/main/resources/META-INF/dox.xml
<?xml version="1.0" encoding="UTF-8"?>
<dox-persistence xmlns="http://doxdb.trajano.net/schema/"
	xsi:schemaLocation="http://doxdb.trajano.net/schema/ ../../../../../doxdb-rest/src/main/resources/META-INF/xsd/dox.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" cors="*">
	<dox name="horse" oob="true" readAll="none">
		<schema version="1" location="horse.json">
			<unique name="horseName" path="$.name" />
			<unique name="horseFei" path="$.fei" />
		</schema>
	</dox>
	<dox name="venue" oob="false" readAll="memory">
		<schema version="1" location="venue.json">
			<unique name="fei" path="$.feiId" />
		</schema>
	</dox>
	<index name="myindex" />
	<index name="maskedindex" />
</dox-persistence>
